SEED: 0
LOG: True

# ENVIRONMENT
ENV_NAME: "CartPole-v1"

# DATASET
DATASET_TYPE: "random"
DATASET_SIZE: 20000

# MLP STRUCTURE
MODEL: 
  HIDDEN_LAYERS: [256, 256] 

# APPROXIMATE INFERENCE
VARIATIONAL_INFERENCE:
  LEARN_SIGMA: False
  WARM_START: False
  PRIOR_TYPE: "gaussian"
  PRIOR_PARAMETERS: {}
  BATCH_SIZE: 32 
  MAX_UPDATE_STEPS: 50000
  LR: 0.001 
  KL_WEIGHT: 1