SEED: 0
LOG: True

# ENVIRONMENT
ENV_NAME: "test_vi_1d"

# MLP STRUCTURE
MODEL: 
  HIDDEN_LAYERS: [32, 32] 

# APPROXIMATE INFERENCE
VARIATIONAL_INFERENCE:
  LEARN_SIGMA: False
  WARM_START: False
  PRIOR_TYPE: "gaussian"
  PRIOR_PARAMETERS: {}
  BATCH_SIZE: 10  
  MAX_UPDATE_STEPS: 20000
  LR: 0.005 
  KL_WEIGHT: 1