SEED: 0
LOG: True

# ENVIRONMENT
ENV_NAME: "test_vi_2d"

# MLP STRUCTURE
MODEL: 
  HIDDEN_LAYERS: [256, 256] 

# APPROXIMATE INFERENCE 
VARIATIONAL_INFERENCE:
  LEARN_SIGMA: False
  WARM_START: False
  PRIOR_TYPE: "gaussian"
  PRIOR_PARAMETERS: {}
  BATCH_SIZE: 32 
  MAX_UPDATE_STEPS: 100000
  LR: 0.001 
  KL_WEIGHT: 1